import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class SavePaymentMethodDto {
  @ApiProperty({
    description:
      'Card token generated by the Mercado Pago client SDK. The card number, CVV, and expiration date must never be sent directly to the backend.',
    example: 'ff8080814c8dd1230...',
  })
  @IsNotEmpty()
  @IsString()
  card_token_id: string;

  @ApiPropertyOptional({
    description: 'Sets this card as the user default payment method',
    example: true,
  })
  @IsOptional()
  @IsBoolean()
  is_default?: boolean;
}
