services:
  # --- Banco de Dados PostgreSQL ---
  db:
    image: postgres:16
    container_name: meatshop-postgres
    environment:
      - POSTGRES_DB=meatshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./meatshop-backend/db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # --- Backend NestJS ---
  backend:
    build: ./meatshop-backend
    container_name: meatshop-backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001

      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=meatshop
      - DB_SYNCHRONIZE=false

      - LOG_LEVEL=info
      - LOG_DIR=logs
      - LOG_MAX_DAYS=14d
      - TZ=America/Sao_Paulo

    volumes:
      - ./meatshop-backend/logs:/usr/src/app/logs
      - ./meatshop-backend/migrations:/usr/src/app/migrations

    restart: unless-stopped

  frontend:
    build: ./meatshop-main
    container_name: meatshop-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped