services:
  backend:
    build: ./meatshop-backend
    container_name: meatshop-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_TYPE=sqlite
      - DB_PATH=./data/meatshop.db
      - DB_SYNCHRONIZE=true
      - LOG_LEVEL=info
      - LOG_DIR=logs
      - LOG_MAX_DAYS=14d
      - TZ=America/Sao_Paulo
    volumes:
      - ./meatshop-backend/data:/usr/src/app/data
      - ./meatshop-backend/logs:/usr/src/app/logs   
    restart: unless-stopped

  frontend:
    build: ./meatshop-main
    container_name: meatshop-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped