export enum UnitPermission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES',
  VIEW_FINANCE = 'VIEW_FINANCE',
  MANAGE_FINANCE = 'MANAGE_FINANCE',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  MANAGE_UNIT = 'MANAGE_UNIT',
}
