"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgePercent, History, Plus, Search, TicketPercent, X } from "lucide-react";
import { apiGet, apiPatch, apiPost } from "@/shared/lib/api";
import { Spinner } from "@/shared/components/ui/spinner";
import { toast } from "@/shared/lib/toast";
import { useManagedUnits } from "@/shared/hooks/use-managed-units";
import { usePanelAccess } from "@/shared/providers/panel-access-provider";
import type { Coupon, CouponResult, CouponType, DiscountType, Redemption } from "./types";

type FormState = { code: string; name: string; description: string; type: CouponType; unit_id: string; allowed_unit_ids: number[]; discount_type: DiscountType; discount_amount: string; maximum_discount: string; minimum_order_value: string; starts_at: string; expires_at: string; total_usage_limit: string; usage_limit_per_user: string; active: boolean };
const emptyForm: FormState = { code: "", name: "", description: "", type: "UNIT", unit_id: "", allowed_unit_ids: [], discount_type: "PERCENTAGE", discount_amount: "", maximum_discount: "", minimum_order_value: "0", starts_at: "", expires_at: "", total_usage_limit: "", usage_limit_per_user: "1", active: true };

export function CouponsScreen() {
  const { user, unitId } = usePanelAccess();
  const { units } = useManagedUnits();
  const isAdmin = user?.global_role === "SUPER_ADMIN";
  const [result, setResult] = useState<CouponResult>({ data: [], meta: { page: 1, total: 0, totalPages: 1 } });
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const [form, setForm] = useState<FormState>(emptyForm); const [editing, setEditing] = useState<Coupon | null>(null);
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const [history, setHistory] = useState<{ coupon: Coupon; items: Redemption[] } | null>(null);
  const query = useMemo(() => new URLSearchParams({ page: String(page), limit: "20", ...(search ? { search } : {}), ...(!isAdmin && unitId ? { unit_id: String(unitId) } : {}) }).toString(), [isAdmin, page, search, unitId]);
  const load = useCallback(async () => { setLoading(true); try { setResult(await apiGet(`/coupons?${query}`, { silent: true })); } finally { setLoading(false); } }, [query]);
  useEffect(() => { if (isAdmin || unitId) void load(); }, [isAdmin, load, unitId]);

  function startCreate() { setEditing(null); setForm({ ...emptyForm, type: isAdmin ? "PLATFORM" : "UNIT", unit_id: !isAdmin && unitId ? String(unitId) : "" }); setOpen(true); }
  function startEdit(coupon: Coupon) { setEditing(coupon); setForm(toForm(coupon)); setOpen(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { const payload = toPayload(form, isAdmin, !!editing); if (editing) await apiPatch(`/coupons/${editing.id}`, payload); else await apiPost("/coupons", payload); toast.success(editing ? "Cupom atualizado." : "Cupom criado."); setOpen(false); await load(); } catch {} finally { setSaving(false); } }
  async function toggle(coupon: Coupon) { try { await apiPatch(`/coupons/${coupon.id}`, { active: !coupon.active }); await load(); } catch {} }
  async function showHistory(coupon: Coupon) { const items = await apiGet(`/coupons/${coupon.id}/redemptions`); setHistory({ coupon, items }); }

  return <section className="mx-auto max-w-7xl space-y-6 p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Cupons</h1><p className="text-sm text-slate-500">{isAdmin ? "Campanhas globais da plataforma e cupons das unidades." : "Cupons exclusivos da unidade selecionada."}</p></div><button onClick={startCreate} className="flex items-center gap-2 rounded-lg bg-red-700 px-4 py-2 font-semibold text-white"><Plus className="size-4" />Novo cupom</button></header>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Cadastrados" value={result.meta.total} icon={TicketPercent} /><Metric label="Ativos na página" value={result.data.filter((item) => item.active).length} icon={BadgePercent} /><Metric label="Usos na página" value={result.data.reduce((sum, item) => sum + item.current_usage_count, 0)} icon={History} /></div>
    <label className="relative block max-w-xl"><Search className="absolute left-3 top-2.5 size-4 text-slate-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Buscar por código ou nome" className="w-full rounded-lg border bg-white py-2 pl-9 pr-3" /></label>
    <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Cupom</th><th className="p-3">Escopo</th><th className="p-3">Desconto</th><th className="p-3">Validade</th><th className="p-3">Utilizações</th><th className="p-3">Status</th><th className="p-3">Ações</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-10 text-center">Carregando...</td></tr> : result.data.length === 0 ? <tr><td colSpan={7} className="p-10 text-center text-slate-500">Nenhum cupom encontrado.</td></tr> : result.data.map((coupon) => <CouponRow key={coupon.id} coupon={coupon} edit={() => startEdit(coupon)} toggle={() => void toggle(coupon)} history={() => void showHistory(coupon)} />)}</tbody></table></div><div className="flex justify-between border-t p-3 text-sm"><span>{result.meta.total} cupom(ns)</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 disabled:opacity-40">Anterior</button><span>{page}/{result.meta.totalPages}</span><button disabled={page >= result.meta.totalPages} onClick={() => setPage(page + 1)} className="rounded border px-3 disabled:opacity-40">Próxima</button></div></div></div>
    {open && <CouponForm form={form} setForm={setForm} units={units} isAdmin={isAdmin} editing={editing} saving={saving} close={() => setOpen(false)} save={save} />}{history && <HistoryModal data={history} close={() => setHistory(null)} />}
  </section>;
}

function toPayload(form: FormState, isAdmin: boolean, editing: boolean) { return { code: form.code, name: form.name, description: form.description || undefined, type: isAdmin ? form.type : "UNIT", unit_id: form.type === "UNIT" ? Number(form.unit_id) : undefined, allowed_unit_ids: form.type === "PLATFORM" ? form.allowed_unit_ids : undefined, discount_type: form.discount_type, discount_amount: Number(form.discount_amount), maximum_discount: form.discount_type === "PERCENTAGE" ? (form.maximum_discount ? Number(form.maximum_discount) : editing ? null : undefined) : undefined, minimum_order_value: Number(form.minimum_order_value || 0), starts_at: new Date(form.starts_at).toISOString(), expires_at: new Date(form.expires_at).toISOString(), total_usage_limit: form.total_usage_limit ? Number(form.total_usage_limit) : editing ? null : undefined, usage_limit_per_user: form.usage_limit_per_user ? Number(form.usage_limit_per_user) : editing ? null : undefined, active: form.active }; }
function toLocal(value: string) { const date = new Date(value); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
function toForm(c: Coupon): FormState { return { code: c.code, name: c.name, description: c.description ?? "", type: c.type, unit_id: c.unit_id ? String(c.unit_id) : "", allowed_unit_ids: c.allowed_units.map((item) => item.unit_id), discount_type: c.discount_type, discount_amount: String(c.discount_amount), maximum_discount: c.maximum_discount ? String(c.maximum_discount) : "", minimum_order_value: String(c.minimum_order_value), starts_at: toLocal(c.starts_at), expires_at: toLocal(c.expires_at), total_usage_limit: c.total_usage_limit ? String(c.total_usage_limit) : "", usage_limit_per_user: c.usage_limit_per_user ? String(c.usage_limit_per_user) : "", active: c.active }; }
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof History }) { return <div className="rounded-xl border bg-white p-4"><div className="flex items-center gap-2 text-slate-500"><Icon className="size-4" />{label}</div><strong className="mt-2 block text-2xl">{value}</strong></div>; }
function CouponRow({ coupon, edit, toggle, history }: { coupon: Coupon; edit: () => void; toggle: () => void; history: () => void }) { const expired = new Date(coupon.expires_at) <= new Date(); return <tr className="border-t"><td className="p-3"><strong>{coupon.code}</strong><span className="block text-xs text-slate-500">{coupon.name}</span></td><td className="p-3">{coupon.type === "UNIT" ? coupon.unit?.name : coupon.allowed_units.length ? `${coupon.allowed_units.length} unidade(s)` : "Toda a plataforma"}</td><td className="p-3">{coupon.discount_type === "PERCENTAGE" ? `${coupon.discount_amount}%` : Number(coupon.discount_amount).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td className="p-3">{new Date(coupon.expires_at).toLocaleDateString("pt-BR")}</td><td className="p-3">{coupon.current_usage_count}{coupon.total_usage_limit ? ` / ${coupon.total_usage_limit}` : ""}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${coupon.active && !expired ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{expired ? "Expirado" : coupon.active ? "Ativo" : "Inativo"}</span></td><td className="p-3"><div className="flex gap-3"><button onClick={edit} className="font-medium text-red-700">Editar</button><button onClick={toggle}>{coupon.active ? "Desativar" : "Ativar"}</button><button onClick={history}>Usos</button></div></td></tr>; }

function CouponForm({ form, setForm, units, isAdmin, editing, saving, close, save }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; units: Array<{ id: number; name: string }>; isAdmin: boolean; editing: Coupon | null; saving: boolean; close: () => void; save: (e: React.FormEvent) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={save} className="max-h-[92vh] w-full max-w-3xl space-y-4 overflow-y-auto rounded-xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{editing ? "Editar cupom" : "Novo cupom"}</h2><p className="text-sm text-slate-500">Defina escopo, benefício e limites de utilização.</p></div><button type="button" onClick={close}><X /></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Código"><input required disabled={!!editing} value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} pattern="[A-Za-z0-9_-]+" className="input" /></Field><Field label="Nome"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="input" /></Field></div>
      <Field label="Descrição"><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={2} className="input" /></Field>{isAdmin && <Field label="Tipo"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as CouponType, unit_id: "", allowed_unit_ids: [] })} className="input"><option value="PLATFORM">Plataforma</option><option value="UNIT">Unidade</option></select></Field>}{form.type === "UNIT" && <Field label="Unidade"><select required value={form.unit_id} disabled={!isAdmin} onChange={(e) => setForm({ ...form, unit_id: e.target.value })} className="input"><option value="">Selecione</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field>}{form.type === "PLATFORM" && <div><span className="text-sm font-medium">Unidades permitidas</span><p className="mb-2 text-xs text-slate-500">Sem seleção significa todas as unidades.</p><div className="grid max-h-32 gap-2 overflow-y-auto rounded border p-3 sm:grid-cols-2">{units.map((unit) => <label key={unit.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.allowed_unit_ids.includes(unit.id)} onChange={() => setForm({ ...form, allowed_unit_ids: form.allowed_unit_ids.includes(unit.id) ? form.allowed_unit_ids.filter((id) => id !== unit.id) : [...form.allowed_unit_ids, unit.id] })} />{unit.name}</label>)}</div></div>}
      <div className="grid gap-4 sm:grid-cols-3"><Field label="Modalidade"><select value={form.discount_type} onChange={(e) => setForm({ ...form, discount_type: e.target.value as DiscountType, maximum_discount: "" })} className="input"><option value="PERCENTAGE">Percentual</option><option value="FIXED">Valor fixo</option></select></Field><Field label={form.discount_type === "PERCENTAGE" ? "Desconto (%)" : "Desconto (R$)"}><input required type="number" min="0.01" max={form.discount_type === "PERCENTAGE" ? 100 : undefined} step="0.01" value={form.discount_amount} onChange={(e) => setForm({ ...form, discount_amount: e.target.value })} className="input" /></Field>{form.discount_type === "PERCENTAGE" && <Field label="Teto do desconto (R$)"><input type="number" min="0.01" step="0.01" value={form.maximum_discount} onChange={(e) => setForm({ ...form, maximum_discount: e.target.value })} className="input" /></Field>}</div>
      <div className="grid gap-4 sm:grid-cols-3"><Field label="Pedido mínimo (R$)"><input type="number" min="0" step="0.01" value={form.minimum_order_value} onChange={(e) => setForm({ ...form, minimum_order_value: e.target.value })} className="input" /></Field><Field label="Limite total"><input type="number" min="1" value={form.total_usage_limit} onChange={(e) => setForm({ ...form, total_usage_limit: e.target.value })} className="input" /></Field><Field label="Limite por cliente"><input type="number" min="1" value={form.usage_limit_per_user} onChange={(e) => setForm({ ...form, usage_limit_per_user: e.target.value })} className="input" /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Início"><input required type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} className="input" /></Field><Field label="Término"><input required type="datetime-local" value={form.expires_at} onChange={(e) => setForm({ ...form, expires_at: e.target.value })} className="input" /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />Cupom ativo</label><div className="flex justify-end gap-3"><button type="button" onClick={close} className="rounded border px-4 py-2">Cancelar</button><button disabled={saving} className="flex items-center gap-2 rounded bg-red-700 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving && <Spinner />}{saving ? "Salvando..." : "Salvar"}</button></div></form></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}<div className="mt-1 [&_.input]:w-full [&_.input]:rounded-md [&_.input]:border [&_.input]:px-3 [&_.input]:py-2">{children}</div></label>; }
function HistoryModal({ data, close }: { data: { coupon: Coupon; items: Redemption[] }; close: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Utilizações de {data.coupon.code}</h2><p className="text-sm text-slate-500">Até 500 registros mais recentes.</p></div><button onClick={close}><X /></button></div><div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Data</th><th>Cliente</th><th>Unidade</th><th>Pedido</th><th>Desconto</th><th>Status</th></tr></thead><tbody>{data.items.length === 0 ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">Ainda não utilizado.</td></tr> : data.items.map((item) => <tr key={item.id} className="border-b"><td className="p-2">{new Date(item.redeemed_at).toLocaleString("pt-BR")}</td><td>{item.user?.name}</td><td>{item.unit?.name}</td><td>#{item.order_id}</td><td>{Number(item.discount_amount).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td>{item.status === "REDEEMED" ? "Utilizado" : "Liberado"}</td></tr>)}</tbody></table></div></div></div>; }
